### ISSUE TITLE
Some verbosity sometimes helpful

### ISSUE THREAD

**Issue by sen1** [bahobab/TomeRater#1]
https://github.com/bahobab/TomeRater/blob/c8420e0107e5762b9a4e7791c1ef722427b605ba/TomeRater.py#L13-L14

Some verbosity is sometimes very helpful. I would add a line:
```
 def change_email(self, address): 
     self.email = address 
     print("User " + self.name + " now has email: "+self.email)
```

**Comment by bahobab** [comment]
issue fixed
