### ISSUE TITLE
Wrong implementation

### ISSUE THREAD

**Issue by sen1** [bahobab/TomeRater#2]
https://github.com/bahobab/TomeRater/blob/c8420e0107e5762b9a4e7791c1ef722427b605ba/TomeRater.py#L19-L20

Read the instructions again. Users are same when both name and email are same.
```
def __eq__(self, other_user):
        if self.name == other_user.name and self.email == other_user.email:
            return True
        return False
```

**Comment by bahobab** [comment]
Issue fiexed
