### ISSUE TITLE
No need to compare with None

### ISSUE THREAD

**Issue by sen1** [bahobab/TomeRater#3]
https://github.com/bahobab/TomeRater/blob/c8420e0107e5762b9a4e7791c1ef722427b605ba/TomeRater.py#L32-L35

No need to compare with `None`. If a variable is `None`, you can simply use if statement to check.
```
     if value: 
         n += 1 
         total_rating += value 
 return total_rating / float(n) 
```

Also make sure to avoid integer division.

**Comment by bahobab** [comment]
Issue corrected
