### ISSUE TITLE
Wrong place

### ISSUE THREAD

**Issue by sen1** [bahobab/TomeRater#4]
https://github.com/bahobab/TomeRater/blob/c8420e0107e5762b9a4e7791c1ef722427b605ba/TomeRater.py#L49-L58

This is a wrong place to put this helper function. It should not be part of `Book` class. Imagine you have 1 million books, then each book object will have a list of 1 million values stored inside. Also begs the question which list is up to date!

**Comment by bahobab** [comment]
Correct. thanks for pointing this out. Implementation corrected
