### ISSUE TITLE
Wrong implementation

### ISSUE THREAD

**Issue by sen1** [bahobab/TomeRater#7]
https://github.com/bahobab/TomeRater/blob/c8420e0107e5762b9a4e7791c1ef722427b605ba/TomeRater.py#L149-L176

Read the concept of inheritance in python. When you make a class inherited from a super class, all its methods become available in the child class automatically. You only need to add those extra methods that you need.

You only need the author methods. Here is the correct answer:
```
class Fiction(Book):
    def __init__(self, title, author, isbn):
        Book.__init__(self, title, isbn)
        self.author = author

    def get_author(self):
        return self.author

    def __repr__(self):
        return self.title + " by " + self.author
```

**Comment by bahobab** [comment]
Correct!
